name: main
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Run
        run: '"$(wget -O- lesiw.io/run | sh)" -v'
      - name: Re-run
        run: 'out/run-linux-x86_64 -v'
